// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

// Protobuf Java Version: 3.25.1
package com.smartretail;

public final class CheckoutProto {
  private CheckoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckoutRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.smartretail.CheckoutRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string productIds = 1;</code>
     * @return A list containing the productIds.
     */
    java.util.List<java.lang.String>
        getProductIdsList();
    /**
     * <code>repeated string productIds = 1;</code>
     * @return The count of productIds.
     */
    int getProductIdsCount();
    /**
     * <code>repeated string productIds = 1;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    java.lang.String getProductIds(int index);
    /**
     * <code>repeated string productIds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    com.google.protobuf.ByteString
        getProductIdsBytes(int index);

    /**
     * <code>repeated int32 quantities = 2;</code>
     * @return A list containing the quantities.
     */
    java.util.List<java.lang.Integer> getQuantitiesList();
    /**
     * <code>repeated int32 quantities = 2;</code>
     * @return The count of quantities.
     */
    int getQuantitiesCount();
    /**
     * <code>repeated int32 quantities = 2;</code>
     * @param index The index of the element to return.
     * @return The quantities at the given index.
     */
    int getQuantities(int index);
  }
  /**
   * Protobuf type {@code com.smartretail.CheckoutRequest}
   */
  public static final class CheckoutRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.smartretail.CheckoutRequest)
      CheckoutRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckoutRequest.newBuilder() to construct.
    private CheckoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckoutRequest() {
      productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      quantities_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckoutRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartretail.CheckoutProto.CheckoutRequest.class, com.smartretail.CheckoutProto.CheckoutRequest.Builder.class);
    }

    public static final int PRODUCTIDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList productIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string productIds = 1;</code>
     * @return A list containing the productIds.
     */
    public com.google.protobuf.ProtocolStringList
        getProductIdsList() {
      return productIds_;
    }
    /**
     * <code>repeated string productIds = 1;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated string productIds = 1;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public java.lang.String getProductIds(int index) {
      return productIds_.get(index);
    }
    /**
     * <code>repeated string productIds = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    public com.google.protobuf.ByteString
        getProductIdsBytes(int index) {
      return productIds_.getByteString(index);
    }

    public static final int QUANTITIES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList quantities_ =
        emptyIntList();
    /**
     * <code>repeated int32 quantities = 2;</code>
     * @return A list containing the quantities.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getQuantitiesList() {
      return quantities_;
    }
    /**
     * <code>repeated int32 quantities = 2;</code>
     * @return The count of quantities.
     */
    public int getQuantitiesCount() {
      return quantities_.size();
    }
    /**
     * <code>repeated int32 quantities = 2;</code>
     * @param index The index of the element to return.
     * @return The quantities at the given index.
     */
    public int getQuantities(int index) {
      return quantities_.getInt(index);
    }
    private int quantitiesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < productIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productIds_.getRaw(i));
      }
      if (getQuantitiesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(quantitiesMemoizedSerializedSize);
      }
      for (int i = 0; i < quantities_.size(); i++) {
        output.writeInt32NoTag(quantities_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < productIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(productIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProductIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < quantities_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(quantities_.getInt(i));
        }
        size += dataSize;
        if (!getQuantitiesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        quantitiesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smartretail.CheckoutProto.CheckoutRequest)) {
        return super.equals(obj);
      }
      com.smartretail.CheckoutProto.CheckoutRequest other = (com.smartretail.CheckoutProto.CheckoutRequest) obj;

      if (!getProductIdsList()
          .equals(other.getProductIdsList())) return false;
      if (!getQuantitiesList()
          .equals(other.getQuantitiesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductIdsCount() > 0) {
        hash = (37 * hash) + PRODUCTIDS_FIELD_NUMBER;
        hash = (53 * hash) + getProductIdsList().hashCode();
      }
      if (getQuantitiesCount() > 0) {
        hash = (37 * hash) + QUANTITIES_FIELD_NUMBER;
        hash = (53 * hash) + getQuantitiesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.smartretail.CheckoutProto.CheckoutRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.smartretail.CheckoutProto.CheckoutRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.CheckoutProto.CheckoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smartretail.CheckoutProto.CheckoutRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.smartretail.CheckoutRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.smartretail.CheckoutRequest)
        com.smartretail.CheckoutProto.CheckoutRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smartretail.CheckoutProto.CheckoutRequest.class, com.smartretail.CheckoutProto.CheckoutRequest.Builder.class);
      }

      // Construct using com.smartretail.CheckoutProto.CheckoutRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        quantities_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutRequest_descriptor;
      }

      @java.lang.Override
      public com.smartretail.CheckoutProto.CheckoutRequest getDefaultInstanceForType() {
        return com.smartretail.CheckoutProto.CheckoutRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.smartretail.CheckoutProto.CheckoutRequest build() {
        com.smartretail.CheckoutProto.CheckoutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smartretail.CheckoutProto.CheckoutRequest buildPartial() {
        com.smartretail.CheckoutProto.CheckoutRequest result = new com.smartretail.CheckoutProto.CheckoutRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.smartretail.CheckoutProto.CheckoutRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          productIds_.makeImmutable();
          result.productIds_ = productIds_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          quantities_.makeImmutable();
          result.quantities_ = quantities_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smartretail.CheckoutProto.CheckoutRequest) {
          return mergeFrom((com.smartretail.CheckoutProto.CheckoutRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smartretail.CheckoutProto.CheckoutRequest other) {
        if (other == com.smartretail.CheckoutProto.CheckoutRequest.getDefaultInstance()) return this;
        if (!other.productIds_.isEmpty()) {
          if (productIds_.isEmpty()) {
            productIds_ = other.productIds_;
            bitField0_ |= 0x00000001;
          } else {
            ensureProductIdsIsMutable();
            productIds_.addAll(other.productIds_);
          }
          onChanged();
        }
        if (!other.quantities_.isEmpty()) {
          if (quantities_.isEmpty()) {
            quantities_ = other.quantities_;
            quantities_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureQuantitiesIsMutable();
            quantities_.addAll(other.quantities_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureProductIdsIsMutable();
                productIds_.add(s);
                break;
              } // case 10
              case 16: {
                int v = input.readInt32();
                ensureQuantitiesIsMutable();
                quantities_.addInt(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureQuantitiesIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  quantities_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureProductIdsIsMutable() {
        if (!productIds_.isModifiable()) {
          productIds_ = new com.google.protobuf.LazyStringArrayList(productIds_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @return A list containing the productIds.
       */
      public com.google.protobuf.ProtocolStringList
          getProductIdsList() {
        productIds_.makeImmutable();
        return productIds_;
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @return The count of productIds.
       */
      public int getProductIdsCount() {
        return productIds_.size();
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @param index The index of the element to return.
       * @return The productIds at the given index.
       */
      public java.lang.String getProductIds(int index) {
        return productIds_.get(index);
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the productIds at the given index.
       */
      public com.google.protobuf.ByteString
          getProductIdsBytes(int index) {
        return productIds_.getByteString(index);
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @param index The index to set the value at.
       * @param value The productIds to set.
       * @return This builder for chaining.
       */
      public Builder setProductIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @param value The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @param values The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllProductIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureProductIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productIds_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductIds() {
        productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 1;</code>
       * @param value The bytes of the productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList quantities_ = emptyIntList();
      private void ensureQuantitiesIsMutable() {
        if (!quantities_.isModifiable()) {
          quantities_ = makeMutableCopy(quantities_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @return A list containing the quantities.
       */
      public java.util.List<java.lang.Integer>
          getQuantitiesList() {
        quantities_.makeImmutable();
        return quantities_;
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @return The count of quantities.
       */
      public int getQuantitiesCount() {
        return quantities_.size();
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @param index The index of the element to return.
       * @return The quantities at the given index.
       */
      public int getQuantities(int index) {
        return quantities_.getInt(index);
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @param index The index to set the value at.
       * @param value The quantities to set.
       * @return This builder for chaining.
       */
      public Builder setQuantities(
          int index, int value) {

        ensureQuantitiesIsMutable();
        quantities_.setInt(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @param value The quantities to add.
       * @return This builder for chaining.
       */
      public Builder addQuantities(int value) {

        ensureQuantitiesIsMutable();
        quantities_.addInt(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @param values The quantities to add.
       * @return This builder for chaining.
       */
      public Builder addAllQuantities(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureQuantitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, quantities_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 quantities = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantities() {
        quantities_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.smartretail.CheckoutRequest)
    }

    // @@protoc_insertion_point(class_scope:com.smartretail.CheckoutRequest)
    private static final com.smartretail.CheckoutProto.CheckoutRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smartretail.CheckoutProto.CheckoutRequest();
    }

    public static com.smartretail.CheckoutProto.CheckoutRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckoutRequest>
        PARSER = new com.google.protobuf.AbstractParser<CheckoutRequest>() {
      @java.lang.Override
      public CheckoutRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CheckoutRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckoutRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smartretail.CheckoutProto.CheckoutRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckoutResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.smartretail.CheckoutResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double totalPrice = 1;</code>
     * @return The totalPrice.
     */
    double getTotalPrice();

    /**
     * <code>repeated string productIds = 2;</code>
     * @return A list containing the productIds.
     */
    java.util.List<java.lang.String>
        getProductIdsList();
    /**
     * <code>repeated string productIds = 2;</code>
     * @return The count of productIds.
     */
    int getProductIdsCount();
    /**
     * <code>repeated string productIds = 2;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    java.lang.String getProductIds(int index);
    /**
     * <code>repeated string productIds = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    com.google.protobuf.ByteString
        getProductIdsBytes(int index);

    /**
     * <code>repeated int32 quantities = 3;</code>
     * @return A list containing the quantities.
     */
    java.util.List<java.lang.Integer> getQuantitiesList();
    /**
     * <code>repeated int32 quantities = 3;</code>
     * @return The count of quantities.
     */
    int getQuantitiesCount();
    /**
     * <code>repeated int32 quantities = 3;</code>
     * @param index The index of the element to return.
     * @return The quantities at the given index.
     */
    int getQuantities(int index);
  }
  /**
   * Protobuf type {@code com.smartretail.CheckoutResponse}
   */
  public static final class CheckoutResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.smartretail.CheckoutResponse)
      CheckoutResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckoutResponse.newBuilder() to construct.
    private CheckoutResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckoutResponse() {
      productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      quantities_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CheckoutResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartretail.CheckoutProto.CheckoutResponse.class, com.smartretail.CheckoutProto.CheckoutResponse.Builder.class);
    }

    public static final int TOTALPRICE_FIELD_NUMBER = 1;
    private double totalPrice_ = 0D;
    /**
     * <code>double totalPrice = 1;</code>
     * @return The totalPrice.
     */
    @java.lang.Override
    public double getTotalPrice() {
      return totalPrice_;
    }

    public static final int PRODUCTIDS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList productIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string productIds = 2;</code>
     * @return A list containing the productIds.
     */
    public com.google.protobuf.ProtocolStringList
        getProductIdsList() {
      return productIds_;
    }
    /**
     * <code>repeated string productIds = 2;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated string productIds = 2;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public java.lang.String getProductIds(int index) {
      return productIds_.get(index);
    }
    /**
     * <code>repeated string productIds = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    public com.google.protobuf.ByteString
        getProductIdsBytes(int index) {
      return productIds_.getByteString(index);
    }

    public static final int QUANTITIES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList quantities_ =
        emptyIntList();
    /**
     * <code>repeated int32 quantities = 3;</code>
     * @return A list containing the quantities.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getQuantitiesList() {
      return quantities_;
    }
    /**
     * <code>repeated int32 quantities = 3;</code>
     * @return The count of quantities.
     */
    public int getQuantitiesCount() {
      return quantities_.size();
    }
    /**
     * <code>repeated int32 quantities = 3;</code>
     * @param index The index of the element to return.
     * @return The quantities at the given index.
     */
    public int getQuantities(int index) {
      return quantities_.getInt(index);
    }
    private int quantitiesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (java.lang.Double.doubleToRawLongBits(totalPrice_) != 0) {
        output.writeDouble(1, totalPrice_);
      }
      for (int i = 0; i < productIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productIds_.getRaw(i));
      }
      if (getQuantitiesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(quantitiesMemoizedSerializedSize);
      }
      for (int i = 0; i < quantities_.size(); i++) {
        output.writeInt32NoTag(quantities_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(totalPrice_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, totalPrice_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < productIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(productIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProductIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < quantities_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(quantities_.getInt(i));
        }
        size += dataSize;
        if (!getQuantitiesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        quantitiesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smartretail.CheckoutProto.CheckoutResponse)) {
        return super.equals(obj);
      }
      com.smartretail.CheckoutProto.CheckoutResponse other = (com.smartretail.CheckoutProto.CheckoutResponse) obj;

      if (java.lang.Double.doubleToLongBits(getTotalPrice())
          != java.lang.Double.doubleToLongBits(
              other.getTotalPrice())) return false;
      if (!getProductIdsList()
          .equals(other.getProductIdsList())) return false;
      if (!getQuantitiesList()
          .equals(other.getQuantitiesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTALPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTotalPrice()));
      if (getProductIdsCount() > 0) {
        hash = (37 * hash) + PRODUCTIDS_FIELD_NUMBER;
        hash = (53 * hash) + getProductIdsList().hashCode();
      }
      if (getQuantitiesCount() > 0) {
        hash = (37 * hash) + QUANTITIES_FIELD_NUMBER;
        hash = (53 * hash) + getQuantitiesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.smartretail.CheckoutProto.CheckoutResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.smartretail.CheckoutProto.CheckoutResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.CheckoutProto.CheckoutResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smartretail.CheckoutProto.CheckoutResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.smartretail.CheckoutResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.smartretail.CheckoutResponse)
        com.smartretail.CheckoutProto.CheckoutResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smartretail.CheckoutProto.CheckoutResponse.class, com.smartretail.CheckoutProto.CheckoutResponse.Builder.class);
      }

      // Construct using com.smartretail.CheckoutProto.CheckoutResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        totalPrice_ = 0D;
        productIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        quantities_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smartretail.CheckoutProto.internal_static_com_smartretail_CheckoutResponse_descriptor;
      }

      @java.lang.Override
      public com.smartretail.CheckoutProto.CheckoutResponse getDefaultInstanceForType() {
        return com.smartretail.CheckoutProto.CheckoutResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.smartretail.CheckoutProto.CheckoutResponse build() {
        com.smartretail.CheckoutProto.CheckoutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smartretail.CheckoutProto.CheckoutResponse buildPartial() {
        com.smartretail.CheckoutProto.CheckoutResponse result = new com.smartretail.CheckoutProto.CheckoutResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.smartretail.CheckoutProto.CheckoutResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.totalPrice_ = totalPrice_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          productIds_.makeImmutable();
          result.productIds_ = productIds_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          quantities_.makeImmutable();
          result.quantities_ = quantities_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smartretail.CheckoutProto.CheckoutResponse) {
          return mergeFrom((com.smartretail.CheckoutProto.CheckoutResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smartretail.CheckoutProto.CheckoutResponse other) {
        if (other == com.smartretail.CheckoutProto.CheckoutResponse.getDefaultInstance()) return this;
        if (other.getTotalPrice() != 0D) {
          setTotalPrice(other.getTotalPrice());
        }
        if (!other.productIds_.isEmpty()) {
          if (productIds_.isEmpty()) {
            productIds_ = other.productIds_;
            bitField0_ |= 0x00000002;
          } else {
            ensureProductIdsIsMutable();
            productIds_.addAll(other.productIds_);
          }
          onChanged();
        }
        if (!other.quantities_.isEmpty()) {
          if (quantities_.isEmpty()) {
            quantities_ = other.quantities_;
            quantities_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureQuantitiesIsMutable();
            quantities_.addAll(other.quantities_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                totalPrice_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureProductIdsIsMutable();
                productIds_.add(s);
                break;
              } // case 18
              case 24: {
                int v = input.readInt32();
                ensureQuantitiesIsMutable();
                quantities_.addInt(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureQuantitiesIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  quantities_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double totalPrice_ ;
      /**
       * <code>double totalPrice = 1;</code>
       * @return The totalPrice.
       */
      @java.lang.Override
      public double getTotalPrice() {
        return totalPrice_;
      }
      /**
       * <code>double totalPrice = 1;</code>
       * @param value The totalPrice to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPrice(double value) {

        totalPrice_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double totalPrice = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        totalPrice_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureProductIdsIsMutable() {
        if (!productIds_.isModifiable()) {
          productIds_ = new com.google.protobuf.LazyStringArrayList(productIds_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @return A list containing the productIds.
       */
      public com.google.protobuf.ProtocolStringList
          getProductIdsList() {
        productIds_.makeImmutable();
        return productIds_;
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @return The count of productIds.
       */
      public int getProductIdsCount() {
        return productIds_.size();
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @param index The index of the element to return.
       * @return The productIds at the given index.
       */
      public java.lang.String getProductIds(int index) {
        return productIds_.get(index);
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the productIds at the given index.
       */
      public com.google.protobuf.ByteString
          getProductIdsBytes(int index) {
        return productIds_.getByteString(index);
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @param index The index to set the value at.
       * @param value The productIds to set.
       * @return This builder for chaining.
       */
      public Builder setProductIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @param value The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @param values The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllProductIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureProductIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productIds_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductIds() {
        productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string productIds = 2;</code>
       * @param value The bytes of the productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList quantities_ = emptyIntList();
      private void ensureQuantitiesIsMutable() {
        if (!quantities_.isModifiable()) {
          quantities_ = makeMutableCopy(quantities_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @return A list containing the quantities.
       */
      public java.util.List<java.lang.Integer>
          getQuantitiesList() {
        quantities_.makeImmutable();
        return quantities_;
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @return The count of quantities.
       */
      public int getQuantitiesCount() {
        return quantities_.size();
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @param index The index of the element to return.
       * @return The quantities at the given index.
       */
      public int getQuantities(int index) {
        return quantities_.getInt(index);
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @param index The index to set the value at.
       * @param value The quantities to set.
       * @return This builder for chaining.
       */
      public Builder setQuantities(
          int index, int value) {

        ensureQuantitiesIsMutable();
        quantities_.setInt(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @param value The quantities to add.
       * @return This builder for chaining.
       */
      public Builder addQuantities(int value) {

        ensureQuantitiesIsMutable();
        quantities_.addInt(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @param values The quantities to add.
       * @return This builder for chaining.
       */
      public Builder addAllQuantities(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureQuantitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, quantities_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 quantities = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantities() {
        quantities_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.smartretail.CheckoutResponse)
    }

    // @@protoc_insertion_point(class_scope:com.smartretail.CheckoutResponse)
    private static final com.smartretail.CheckoutProto.CheckoutResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smartretail.CheckoutProto.CheckoutResponse();
    }

    public static com.smartretail.CheckoutProto.CheckoutResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckoutResponse>
        PARSER = new com.google.protobuf.AbstractParser<CheckoutResponse>() {
      @java.lang.Override
      public CheckoutResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CheckoutResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckoutResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smartretail.CheckoutProto.CheckoutResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartretail_CheckoutRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartretail_CheckoutRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartretail_CheckoutResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartretail_CheckoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016checkout.proto\022\017com.smartretail\"9\n\017Che" +
      "ckoutRequest\022\022\n\nproductIds\030\001 \003(\t\022\022\n\nquan" +
      "tities\030\002 \003(\005\"N\n\020CheckoutResponse\022\022\n\ntota" +
      "lPrice\030\001 \001(\001\022\022\n\nproductIds\030\002 \003(\t\022\022\n\nquan" +
      "tities\030\003 \003(\0052b\n\017CheckoutService\022O\n\010check" +
      "out\022 .com.smartretail.CheckoutRequest\032!." +
      "com.smartretail.CheckoutResponseB\017B\rChec" +
      "koutProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_smartretail_CheckoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartretail_CheckoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartretail_CheckoutRequest_descriptor,
        new java.lang.String[] { "ProductIds", "Quantities", });
    internal_static_com_smartretail_CheckoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smartretail_CheckoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartretail_CheckoutResponse_descriptor,
        new java.lang.String[] { "TotalPrice", "ProductIds", "Quantities", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
