// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

// Protobuf Java Version: 3.25.1
package com.smartretail;

public final class PaymentProto {
  private PaymentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaymentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.smartretail.PaymentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>string cardNumber = 2;</code>
     * @return The cardNumber.
     */
    java.lang.String getCardNumber();
    /**
     * <code>string cardNumber = 2;</code>
     * @return The bytes for cardNumber.
     */
    com.google.protobuf.ByteString
        getCardNumberBytes();

    /**
     * <code>string expiryDate = 3;</code>
     * @return The expiryDate.
     */
    java.lang.String getExpiryDate();
    /**
     * <code>string expiryDate = 3;</code>
     * @return The bytes for expiryDate.
     */
    com.google.protobuf.ByteString
        getExpiryDateBytes();

    /**
     * <code>string cvv = 4;</code>
     * @return The cvv.
     */
    java.lang.String getCvv();
    /**
     * <code>string cvv = 4;</code>
     * @return The bytes for cvv.
     */
    com.google.protobuf.ByteString
        getCvvBytes();
  }
  /**
   * Protobuf type {@code com.smartretail.PaymentRequest}
   */
  public static final class PaymentRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.smartretail.PaymentRequest)
      PaymentRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaymentRequest.newBuilder() to construct.
    private PaymentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaymentRequest() {
      cardNumber_ = "";
      expiryDate_ = "";
      cvv_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaymentRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartretail.PaymentProto.PaymentRequest.class, com.smartretail.PaymentProto.PaymentRequest.Builder.class);
    }

    public static final int AMOUNT_FIELD_NUMBER = 1;
    private double amount_ = 0D;
    /**
     * <code>double amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    public static final int CARDNUMBER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cardNumber_ = "";
    /**
     * <code>string cardNumber = 2;</code>
     * @return The cardNumber.
     */
    @java.lang.Override
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string cardNumber = 2;</code>
     * @return The bytes for cardNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRYDATE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object expiryDate_ = "";
    /**
     * <code>string expiryDate = 3;</code>
     * @return The expiryDate.
     */
    @java.lang.Override
    public java.lang.String getExpiryDate() {
      java.lang.Object ref = expiryDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expiryDate_ = s;
        return s;
      }
    }
    /**
     * <code>string expiryDate = 3;</code>
     * @return The bytes for expiryDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExpiryDateBytes() {
      java.lang.Object ref = expiryDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiryDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CVV_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cvv_ = "";
    /**
     * <code>string cvv = 4;</code>
     * @return The cvv.
     */
    @java.lang.Override
    public java.lang.String getCvv() {
      java.lang.Object ref = cvv_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cvv_ = s;
        return s;
      }
    }
    /**
     * <code>string cvv = 4;</code>
     * @return The bytes for cvv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCvvBytes() {
      java.lang.Object ref = cvv_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cvv_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        output.writeDouble(1, amount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cardNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cardNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expiryDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, expiryDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cvv_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cvv_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, amount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cardNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cardNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expiryDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, expiryDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cvv_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cvv_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smartretail.PaymentProto.PaymentRequest)) {
        return super.equals(obj);
      }
      com.smartretail.PaymentProto.PaymentRequest other = (com.smartretail.PaymentProto.PaymentRequest) obj;

      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!getCardNumber()
          .equals(other.getCardNumber())) return false;
      if (!getExpiryDate()
          .equals(other.getExpiryDate())) return false;
      if (!getCvv()
          .equals(other.getCvv())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + CARDNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getCardNumber().hashCode();
      hash = (37 * hash) + EXPIRYDATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpiryDate().hashCode();
      hash = (37 * hash) + CVV_FIELD_NUMBER;
      hash = (53 * hash) + getCvv().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.smartretail.PaymentProto.PaymentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.smartretail.PaymentProto.PaymentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.PaymentProto.PaymentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smartretail.PaymentProto.PaymentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.smartretail.PaymentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.smartretail.PaymentRequest)
        com.smartretail.PaymentProto.PaymentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smartretail.PaymentProto.PaymentRequest.class, com.smartretail.PaymentProto.PaymentRequest.Builder.class);
      }

      // Construct using com.smartretail.PaymentProto.PaymentRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        amount_ = 0D;
        cardNumber_ = "";
        expiryDate_ = "";
        cvv_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentRequest_descriptor;
      }

      @java.lang.Override
      public com.smartretail.PaymentProto.PaymentRequest getDefaultInstanceForType() {
        return com.smartretail.PaymentProto.PaymentRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.smartretail.PaymentProto.PaymentRequest build() {
        com.smartretail.PaymentProto.PaymentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smartretail.PaymentProto.PaymentRequest buildPartial() {
        com.smartretail.PaymentProto.PaymentRequest result = new com.smartretail.PaymentProto.PaymentRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.smartretail.PaymentProto.PaymentRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.amount_ = amount_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cardNumber_ = cardNumber_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.expiryDate_ = expiryDate_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cvv_ = cvv_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smartretail.PaymentProto.PaymentRequest) {
          return mergeFrom((com.smartretail.PaymentProto.PaymentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smartretail.PaymentProto.PaymentRequest other) {
        if (other == com.smartretail.PaymentProto.PaymentRequest.getDefaultInstance()) return this;
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.getCardNumber().isEmpty()) {
          cardNumber_ = other.cardNumber_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getExpiryDate().isEmpty()) {
          expiryDate_ = other.expiryDate_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getCvv().isEmpty()) {
          cvv_ = other.cvv_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                amount_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 18: {
                cardNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                expiryDate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                cvv_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double amount_ ;
      /**
       * <code>double amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {

        amount_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        amount_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object cardNumber_ = "";
      /**
       * <code>string cardNumber = 2;</code>
       * @return The cardNumber.
       */
      public java.lang.String getCardNumber() {
        java.lang.Object ref = cardNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cardNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cardNumber = 2;</code>
       * @return The bytes for cardNumber.
       */
      public com.google.protobuf.ByteString
          getCardNumberBytes() {
        java.lang.Object ref = cardNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cardNumber = 2;</code>
       * @param value The cardNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCardNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cardNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string cardNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardNumber() {
        cardNumber_ = getDefaultInstance().getCardNumber();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string cardNumber = 2;</code>
       * @param value The bytes for cardNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCardNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cardNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object expiryDate_ = "";
      /**
       * <code>string expiryDate = 3;</code>
       * @return The expiryDate.
       */
      public java.lang.String getExpiryDate() {
        java.lang.Object ref = expiryDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expiryDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expiryDate = 3;</code>
       * @return The bytes for expiryDate.
       */
      public com.google.protobuf.ByteString
          getExpiryDateBytes() {
        java.lang.Object ref = expiryDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expiryDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expiryDate = 3;</code>
       * @param value The expiryDate to set.
       * @return This builder for chaining.
       */
      public Builder setExpiryDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        expiryDate_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string expiryDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiryDate() {
        expiryDate_ = getDefaultInstance().getExpiryDate();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string expiryDate = 3;</code>
       * @param value The bytes for expiryDate to set.
       * @return This builder for chaining.
       */
      public Builder setExpiryDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        expiryDate_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object cvv_ = "";
      /**
       * <code>string cvv = 4;</code>
       * @return The cvv.
       */
      public java.lang.String getCvv() {
        java.lang.Object ref = cvv_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cvv_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cvv = 4;</code>
       * @return The bytes for cvv.
       */
      public com.google.protobuf.ByteString
          getCvvBytes() {
        java.lang.Object ref = cvv_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cvv_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cvv = 4;</code>
       * @param value The cvv to set.
       * @return This builder for chaining.
       */
      public Builder setCvv(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cvv_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string cvv = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCvv() {
        cvv_ = getDefaultInstance().getCvv();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string cvv = 4;</code>
       * @param value The bytes for cvv to set.
       * @return This builder for chaining.
       */
      public Builder setCvvBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cvv_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.smartretail.PaymentRequest)
    }

    // @@protoc_insertion_point(class_scope:com.smartretail.PaymentRequest)
    private static final com.smartretail.PaymentProto.PaymentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smartretail.PaymentProto.PaymentRequest();
    }

    public static com.smartretail.PaymentProto.PaymentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaymentRequest>
        PARSER = new com.google.protobuf.AbstractParser<PaymentRequest>() {
      @java.lang.Override
      public PaymentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaymentRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smartretail.PaymentProto.PaymentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PaymentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.smartretail.PaymentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string transactionId = 2;</code>
     * @return The transactionId.
     */
    java.lang.String getTransactionId();
    /**
     * <code>string transactionId = 2;</code>
     * @return The bytes for transactionId.
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();
  }
  /**
   * Protobuf type {@code com.smartretail.PaymentResponse}
   */
  public static final class PaymentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.smartretail.PaymentResponse)
      PaymentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaymentResponse.newBuilder() to construct.
    private PaymentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaymentResponse() {
      transactionId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaymentResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartretail.PaymentProto.PaymentResponse.class, com.smartretail.PaymentProto.PaymentResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_ = false;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int TRANSACTIONID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object transactionId_ = "";
    /**
     * <code>string transactionId = 2;</code>
     * @return The transactionId.
     */
    @java.lang.Override
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      }
    }
    /**
     * <code>string transactionId = 2;</code>
     * @return The bytes for transactionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transactionId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transactionId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.smartretail.PaymentProto.PaymentResponse)) {
        return super.equals(obj);
      }
      com.smartretail.PaymentProto.PaymentResponse other = (com.smartretail.PaymentProto.PaymentResponse) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getTransactionId()
          .equals(other.getTransactionId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + TRANSACTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.smartretail.PaymentProto.PaymentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.smartretail.PaymentProto.PaymentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.smartretail.PaymentProto.PaymentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.smartretail.PaymentProto.PaymentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.smartretail.PaymentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.smartretail.PaymentResponse)
        com.smartretail.PaymentProto.PaymentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.smartretail.PaymentProto.PaymentResponse.class, com.smartretail.PaymentProto.PaymentResponse.Builder.class);
      }

      // Construct using com.smartretail.PaymentProto.PaymentResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        success_ = false;
        transactionId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.smartretail.PaymentProto.internal_static_com_smartretail_PaymentResponse_descriptor;
      }

      @java.lang.Override
      public com.smartretail.PaymentProto.PaymentResponse getDefaultInstanceForType() {
        return com.smartretail.PaymentProto.PaymentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.smartretail.PaymentProto.PaymentResponse build() {
        com.smartretail.PaymentProto.PaymentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.smartretail.PaymentProto.PaymentResponse buildPartial() {
        com.smartretail.PaymentProto.PaymentResponse result = new com.smartretail.PaymentProto.PaymentResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.smartretail.PaymentProto.PaymentResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.transactionId_ = transactionId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.smartretail.PaymentProto.PaymentResponse) {
          return mergeFrom((com.smartretail.PaymentProto.PaymentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.smartretail.PaymentProto.PaymentResponse other) {
        if (other == com.smartretail.PaymentProto.PaymentResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getTransactionId().isEmpty()) {
          transactionId_ = other.transactionId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                success_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                transactionId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object transactionId_ = "";
      /**
       * <code>string transactionId = 2;</code>
       * @return The transactionId.
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transactionId = 2;</code>
       * @return The bytes for transactionId.
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transactionId = 2;</code>
       * @param value The transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        transactionId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string transactionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionId() {
        transactionId_ = getDefaultInstance().getTransactionId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string transactionId = 2;</code>
       * @param value The bytes for transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        transactionId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.smartretail.PaymentResponse)
    }

    // @@protoc_insertion_point(class_scope:com.smartretail.PaymentResponse)
    private static final com.smartretail.PaymentProto.PaymentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.smartretail.PaymentProto.PaymentResponse();
    }

    public static com.smartretail.PaymentProto.PaymentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaymentResponse>
        PARSER = new com.google.protobuf.AbstractParser<PaymentResponse>() {
      @java.lang.Override
      public PaymentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaymentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.smartretail.PaymentProto.PaymentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartretail_PaymentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartretail_PaymentRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartretail_PaymentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartretail_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\022\017com.smartretail\"U\n\016Paym" +
      "entRequest\022\016\n\006amount\030\001 \001(\001\022\022\n\ncardNumber" +
      "\030\002 \001(\t\022\022\n\nexpiryDate\030\003 \001(\t\022\013\n\003cvv\030\004 \001(\t\"" +
      "9\n\017PaymentResponse\022\017\n\007success\030\001 \001(\010\022\025\n\rt" +
      "ransactionId\030\002 \001(\t2e\n\016PaymentService\022S\n\016" +
      "processPayment\022\037.com.smartretail.Payment" +
      "Request\032 .com.smartretail.PaymentRespons" +
      "eB\016B\014PaymentProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_smartretail_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartretail_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartretail_PaymentRequest_descriptor,
        new java.lang.String[] { "Amount", "CardNumber", "ExpiryDate", "Cvv", });
    internal_static_com_smartretail_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smartretail_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartretail_PaymentResponse_descriptor,
        new java.lang.String[] { "Success", "TransactionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
